#!/bin/bash


while true; do
	source .bashrc
	source /opt/ros/melodic/setup.bash
	echo $PWD
	source Ros_ws/devel/setup.bash
	export ROS_ROBOT_NAME=aucamville_test
	export HW_CONNECTED=False
	export ROS_ENV=DEV
	export ROS_ROBOT_HW=v2
	export HOME=/home/patrick
	xhost +
	#HOME=/tmp 
	#XAUTHORITY=/tmp 
	#runuser -l 'patrick' -c 'gnome-terminal -- roslaunch keylo_bringup wyca.launch sim:=true'
	gnome-terminal -- roslaunch keylo_bringup wyca.launch sim:=true
	sleep 60
done
