#!/bin/bash


while true; do
	source .bashrc
	source /opt/ros/melodic/setup.bash
	source Ros_ws/devel/setup.bash
	export ROS_ROBOT_NAME=aucamville_test
	export HW_CONNECTED=False
	export ROS_ENV=DEV
	export ROS_ROBOT_HW=v2
	export HOME=/home/patrick
	xhost +
	roslaunch keylo_bringup test_no_front.launch sim:=true
	sleep 60
done
